### ISSUE TITLE
[Bug]: Soulmask

### ISSUE THREAD

**Issue by Jaspartan** [pelican-eggs/games-steamcmd#87] opened 2024-09-20 05:17 UTC
### Panel Version

1.0

### Wings Version

1.0

### Service

Soulmask

### Modified

No, I did not modify the egg

### Expected Behavior

I cannot use the Console on the Panel for RCON commands. I talked about it in the Discord. https://discord.com/channels/122900397965705216/1286042597982474330 They suggested I post here about that. I do not know the other information as somebody else installed it. Whatever is most recent I'd assume for Panel version and wings version, I just put 1.0.

### Actual Behavior

When typing RCON commands like "Help", "FPS", "LAP", "SaveAndExit 300", etc. it doesn't do anything at all in the web console (panel).

### Steps To Reproduce

It's something that doesn't work with the current version of the panel I believe. Not a heavily detailed post. Just letting you know! :)

### Install logs

https://google.com

**Comment by QuintenQVD0** [comment] 2024-09-20 05:56
That is expected and can not be fixt.

**Comment by Jaspartan** [comment] 2024-09-20 16:34
It works on other game panels. Just not Pter.

**Comment by gOOvER** [comment] 2024-09-20 16:37
> It works on other game panels. Just not Pter.
It wortks not on other panels. ;) Show me one, where it works.
Ptero have no real console. Its only an API connection from Docker API. So it will not work

**Comment by Jaspartan** [comment] 2024-09-20 16:45
![image](https://github.com/user-attachments/assets/85f35670-7e06-4875-9116-5b5b0e77e4b8)
Told you it works nerd.
https://imgur.com/a/p1JwzHc

**Comment by gOOvER** [comment] 2024-09-20 17:08
> ![image](https://private-user-images.githubusercontent.com/18016544/369485114-85f35670-7e06-4875-9116-5b5b0e77e4b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTEwNTgsIm5iZiI6MTcyNjg1MDc1OCwicGF0aCI6Ii8xODAxNjU0NC8zNjk0ODUxMTQtODVmMzU2NzAtN2UwNi00ODc1LTkxMTYtNWI1YjBlNzdlNGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE2NDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZDk2ZDJkNWNlYTE3Y2IxYzI0MDAzZDYxNGQ0YzI2NzMzNjcyYzRjM2JiOTBjMWJlMjE2MGM3ODg4ZDAxZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._GSMOD7SZgWPcYE-ylsdpHo4Kspv6a3e68JXNADQgf8) Told you it works nerd. https://imgur.com/a/p1JwzHc

lol? they have an own Panel :D So better stay with citadel Severs :D

**Comment by Jaspartan** [comment] 2024-09-20 18:19
You said "It works not on other panels. ;) Show me one, where it works." now how about you get off you high horse and realize this is an issue with the Soulmask Egg. Hmmmm? Just a thought for a thot.

**Comment by QuintenQVD0** [comment] 2024-09-20 18:53
Pterodactyl or pelican can simply not do this. 

So please all keep calm.

**Comment by gOOvER** [comment] 2024-09-21 08:10
> You said "It works not on other panels. ;) Show me one, where it works." now how about you get off you high horse and realize this is an issue with the Soulmask Egg. Hmmmm? Just a thought for a thot.

i dont talk about PAID Panel ;) I talked about OpenSource Panels. But if you like to make it working, ask the Peliocan devs, if they add it for Money ;)

(Ptero dev will not do this)

**Comment by ImKringle** [comment] 2024-09-27 16:08
> You said "It works not on other panels. ;) Show me one, where it works." now how about you get off you high horse and realize this is an issue with the Soulmask Egg. Hmmmm? Just a thought for a thot.

While it *can* be fixed by an update to the egg, what Goover is saying is that it isnt an *egg* issue - the image that runs the executable (that is pulled by the egg) has to include a wrapper to send these commands or the startup command would be absolutely gross to support it otherwise. Alternatively, like he mentioned the panel you use would need changed to provide an actual console and not just a piped output from the container - Speaking as someone who works on adding stuff like this for work, its not quite a "add a line and go" situation xD

Anyone could fix this by submitting a PR to the yolks repo and adding it themselves, its just not something the main contributors will; as its not a bug its just a request - they arent exactly paid to provide all this for free 😓

**Comment by Jaspartan** [comment] 2024-09-27 16:16
No worries, leaving Soulmask anyways. That PvE game will end up dying XD

**Comment by QuintenQVD0** [comment] 2024-10-20 18:20
I am closing this as this is currently to complex for pterodactyl or pelican.

If anyone does not agree that is fine then feel free to open a PR

**Closed by QuintenQVD0** 2024-10-20 18:20 UTC
Labels: bug
